version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME:?err}-mssql-2022
    container_name: ${COMPOSE_PROJECT_NAME:?err}_db
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_backup:/var/opt/mssql/backup
      - type: bind
        source: ./tmp
        target: /tmp
    env_file:
      - ./.env/mssql.env
    networks:
      - compose_network
    restart: always

volumes:
  mssql_data:
  mssql_log:
  mssql_backup:

networks:
  compose_network: